# name of your application
APPLICATION = ee250_lab09

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

QUIET ?= 1

# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1

FEATURES_REQUIRED = periph_adc
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
